// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Go Two
Go Two API


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    Contact: Go Two API Support

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
